"""
ABC PDF reader for normalized resource statements.

The current Step 2.4 uses PDF files generated by ABC-4 as the source of truth.
XML-specific names are kept only as temporary compatibility aliases until a real
XML adapter is implemented.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

from PyPDF2 import PdfReader

from nova.integrations.abc.models import (
    ABCMaterial,
    ABCWork,
    EstimateDocumentMeta,
    EstimatePosition,
    ResourceStatement,
)


_SECTION_MARKERS = {
    "Q9": ("локальная смета",),
    "QM": ("ведомость материальных ресурсов", "материальные ресурсы"),
    "ID": ("исходные данные", "строка данных авс"),
}

_BLOCK_START_RE = re.compile(r"^\d+\s+[0-9A-Za-zА-Яа-я]{2,}(?:-[0-9A-Za-zА-Яа-я]+)+")
_ITEM_LINE_RE = re.compile(
    r"^(?P<position>\d+)\s+"
    r"(?P<code>[0-9A-Za-zА-Яа-я]+(?:-[0-9A-Za-zА-Яа-я]+)+)\s+"
    r"(?P<name>.+?)\s+"
    r"(?P<unit>[A-Za-zА-Яа-я0-9./%+-]+(?:\s+[A-Za-zА-Яа-я0-9./%+-]+)?)\s+"
    r"(?P<quantity>\d[\d ]*(?:,\d+)?)\s+"
    r"(?P<unit_price>\d[\d ]*(?:,\d+)?)\s+"
    r"(?P<total_price>\d[\d ]*(?:,\d+)?)$"
)
_ID_LINE_RE = re.compile(
    r"^(?P<row>\d+)"
    r"(?P<code>[A-ZА-ЯЁ][^']+?)"
    r"'(?P<quantity>[^']*)''(?P<name>[^']+)'(?P<unit>[^*]+)\*?$"
)


def _normalize_whitespace(text: str) -> str:
    return " ".join(text.replace("\xa0", " ").split())


def _parse_number(raw: str) -> float:
    normalized = raw.replace(" ", "").replace(",", ".")
    return float(normalized)


def _extract_first_number(raw: str) -> float:
    match = re.search(r"\d+(?:,\d+)?", raw)
    if match is None:
        raise ValueError(f"Could not extract numeric value from {raw!r}")
    return _parse_number(match.group(0))


def _read_pdf_pages(file_path: Path) -> list[tuple[int, str]]:
    reader = PdfReader(str(file_path))
    pages: list[tuple[int, str]] = []

    for page_number, page in enumerate(reader.pages, start=1):
        text = _normalize_whitespace(page.extract_text() or "")
        if text:
            pages.append((page_number, text))

    return pages


def _detect_section(text: str) -> str | None:
    lowered = text.lower()
    for section, markers in _SECTION_MARKERS.items():
        if any(marker in lowered for marker in markers):
            return section
    return None


def _collect_sections(pages: Iterable[tuple[int, str]]) -> dict[str, list[tuple[int, str]]]:
    sections: dict[str, list[tuple[int, str]]] = {"Q9": [], "QM": [], "ID": []}

    for page_number, text in pages:
        section = _detect_section(text)
        if section is not None:
            sections[section].append((page_number, text))

    return sections


def _extract_project_name(all_text: str) -> str | None:
    patterns = (
        r"construction=([^']+)",
        r"По объекту:\s*[«\"]?([^»\"\n]+)",
        r"Наименование стройки\s*[-–]?\s*([^0-9]+?)(?:Шифр стройки|ЛОКАЛЬНАЯ СМЕТА)",
    )

    for pattern in patterns:
        match = re.search(pattern, all_text, flags=re.IGNORECASE)
        if match is not None:
            return _normalize_whitespace(match.group(1).strip(" '\""))
    return None


def _extract_construction_cipher(all_text: str) -> str | None:
    patterns = (
        r"construction-cipher=([A-Za-z0-9-]+)",
        r"Шифр стройки\s*([A-Za-z0-9-]+)",
    )

    for pattern in patterns:
        match = re.search(pattern, all_text, flags=re.IGNORECASE)
        if match is not None:
            return match.group(1)
    return None


def _extract_estimate_code(all_text: str) -> str | None:
    patterns = (
        r"\bЭ\d+\b",
        r"\b\d{1,2}-\d{2}-\d{2}\b",
        r"\b\d{8}\b",
    )

    for pattern in patterns:
        match = re.search(pattern, all_text)
        if match is not None:
            return match.group(0)
    return None


def _build_meta(file_path: Path, sections: dict[str, list[tuple[int, str]]]) -> EstimateDocumentMeta:
    all_text = "\n".join(text for _, text in sections["Q9"] + sections["QM"] + sections["ID"])
    page_ranges = {
        section: [page for page, _ in pages]
        for section, pages in sections.items()
        if pages
    }
    return EstimateDocumentMeta(
        source_file=str(file_path),
        project_name=_extract_project_name(all_text),
        construction_cipher=_extract_construction_cipher(all_text),
        estimate_code=_extract_estimate_code(all_text),
        document_kind="abc_pdf_statement",
        page_ranges=page_ranges,
    )


def _iter_blocks(section_pages: Iterable[tuple[int, str]]) -> list[tuple[int, str]]:
    blocks: list[tuple[int, str]] = []

    for page_number, text in section_pages:
        current: list[str] = []

        for raw_line in text.splitlines():
            line = _normalize_whitespace(raw_line)
            if not line:
                continue
            if line.lower().startswith(("страниц -", "раздел ", "итого ", "всего ")):
                if current:
                    blocks.append((page_number, " ".join(current)))
                    current = []
                continue
            if line.lower().startswith("из них") or re.match(r"^\d+\.\d", line):
                if current:
                    blocks.append((page_number, " ".join(current)))
                    current = []
                continue
            if _BLOCK_START_RE.match(line):
                if current:
                    blocks.append((page_number, " ".join(current)))
                current = [line]
                continue
            if current:
                current.append(line)

        if current:
            blocks.append((page_number, " ".join(current)))

    return blocks


def _parse_block(block: str, page_number: int, position_type: str, section_name: str) -> EstimatePosition | None:
    truncated = block.split(" из них:", 1)[0].strip()
    match = _ITEM_LINE_RE.match(_normalize_whitespace(truncated))
    if match is None:
        return None

    return EstimatePosition(
        position_number=int(match.group("position")),
        code=match.group("code"),
        name=match.group("name"),
        unit=match.group("unit"),
        quantity=_parse_number(match.group("quantity")),
        unit_price=_parse_number(match.group("unit_price")),
        total_price=_parse_number(match.group("total_price")),
        position_type=position_type,  # type: ignore[arg-type]
        section_name=section_name,
        source_page=page_number,
    )


def _parse_q9_positions(section_pages: Iterable[tuple[int, str]]) -> list[EstimatePosition]:
    positions: list[EstimatePosition] = []
    for page_number, block in _iter_blocks(section_pages):
        position = _parse_block(block, page_number, "work", "Q9")
        if position is not None:
            positions.append(position)
    return positions


def _parse_qm_positions(section_pages: Iterable[tuple[int, str]]) -> list[EstimatePosition]:
    positions: list[EstimatePosition] = []
    for page_number, block in _iter_blocks(section_pages):
        position = _parse_block(block, page_number, "material", "QM")
        if position is not None:
            positions.append(position)
    return positions


def _parse_id_fallback(section_pages: Iterable[tuple[int, str]]) -> list[EstimatePosition]:
    positions: list[EstimatePosition] = []

    for page_number, text in section_pages:
        for raw_line in text.splitlines():
            line = _normalize_whitespace(raw_line)
            if not line or line.startswith("ИСХОДНЫЕ ДАННЫЕ"):
                continue

            match = _ID_LINE_RE.match(line)
            if match is None:
                continue

            code = _normalize_whitespace(match.group("code")).split("(", 1)[0]
            positions.append(
                EstimatePosition(
                    position_number=int(match.group("row")),
                    code=code,
                    name=_normalize_whitespace(match.group("name")),
                    unit=_normalize_whitespace(match.group("unit")),
                    quantity=_extract_first_number(match.group("quantity")),
                    unit_price=None,
                    total_price=None,
                    position_type="work",
                    section_name="ID",
                    source_page=page_number,
                )
            )

    return positions


def _positions_to_works(positions: Iterable[EstimatePosition]) -> list[ABCWork]:
    return [
        ABCWork(
            code=position.code,
            name=position.name,
            unit=position.unit,
            quantity=position.quantity,
            price=position.unit_price,
        )
        for position in positions
    ]


def _positions_to_materials(positions: Iterable[EstimatePosition]) -> list[ABCMaterial]:
    return [
        ABCMaterial(
            code=position.code,
            name=position.name,
            unit=position.unit,
            quantity=position.quantity,
            price=position.unit_price,
        )
        for position in positions
    ]


def read_abc_document(file_path: str | Path) -> ResourceStatement:
    """Parse an ABC-generated PDF document into a normalized resource statement."""
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"ABC PDF document not found: {path}")
    if path.suffix.lower() != ".pdf":
        raise ValueError(f"Unsupported ABC document format: {path.suffix or '<none>'}")

    pages = _read_pdf_pages(path)
    if not pages:
        raise ValueError(f"ABC PDF document is empty or unreadable: {path}")

    sections = _collect_sections(pages)
    if not any(sections.values()):
        raise ValueError("ABC PDF document does not contain Q9/QM/ID sections.")

    q9_positions = _parse_q9_positions(sections["Q9"])
    qm_positions = _parse_qm_positions(sections["QM"])
    if not q9_positions and sections["ID"]:
        q9_positions = _parse_id_fallback(sections["ID"])

    positions = [*q9_positions, *qm_positions]
    if not positions:
        raise ValueError("ABC PDF document does not contain parsable work/material positions.")

    return ResourceStatement(
        meta=_build_meta(path, sections),
        positions=positions,
        works=_positions_to_works(q9_positions),
        materials=_positions_to_materials(qm_positions),
        total_works_cost=sum(
            position.total_price or 0.0 for position in q9_positions if position.total_price is not None
        )
        or None,
        total_materials_cost=sum(
            position.total_price or 0.0 for position in qm_positions if position.total_price is not None
        )
        or None,
    )


def read_abc_xml(file_path: str | Path) -> ResourceStatement:
    """Compatibility alias preserved until a real XML adapter is implemented."""
    return read_abc_document(file_path)


__all__ = ["read_abc_document", "read_abc_xml"]
